version: "1"
rules:
  - base: master
    upstream: The-OpenROAD-Project:master
    mergeMethod: none
    assignees:
      - donn
    reviewers:
      - donn
    conflictReviewers:
      - donn
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"